version: '3'

services:
  bull-monitor:
    image: bull-monitor:latest
    build:
      context: .
      args:
        BUILD_VERSION: local
    ports:
      - 3000:3000
    env_file:
      - ./environments/local.env
    environment:
      UI: bull-board
      REDIS_HOST: localhost
      REDIS_PORT: 12312
      PORT: 3000
 